spring.application.name=backend

spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB

spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=${JWT_KEY}